### ISSUE TITLE
blockstack-cli fails in certain connections

### ISSUE THREAD

**Issue by TravisLittlechilds** [stx-labs/stacks.js#75] opened 2016-04-08 08:57 UTC
registering and updating fails when trying from my work connection, but works from a home connection.

info, price, balance, deposit all seem to work.

This happens after a reboot, so it doesn't seem to be a process failing.

**Comment by muneeb-ali** [comment] 2016-04-08 15:43
@TravisLittlechilds Thanks for reporting this. Are you using the same laptop at home and at work? Only the network connection is changing? I'm trying to figure out if this is a firewall issue and blockstack server's port is blocked in your office connection or not.

**Comment by TravisLittlechilds** [comment] 2016-04-08 15:45
It is the same computer and only the network connection changes. I am inclined to believe it is a network issue

**Comment by muneeb-ali** [comment] 2016-04-08 15:53
I'm pretty sure it's a firewall issue. I can help you run certain commands to confirm that port 6264 (used by blockstack-server) is blocked or not.

Can you paste the response of:

> $ blockstack info 

Thanks for reporting this. It tells us that we need to display an appropriate error to the CLI user if the CLI can't talk to the server because of network issues.

**Comment by TravisLittlechilds** [comment] 2016-04-08 16:09
{
    "advanced_mode": "false",
    "cli_version": "0.0.12.7",
    "consensus_hash": "b7c188c635aca9c9f9c4adc4d8f8200d",
    "last_block_processed": 406316,
    "last_block_seen": 406323,
    "server_alive": true,
    "server_host": "server.blockstack.org",
    "server_port": "6264",
    "server_version": "0.0.10.3"
}

**Comment by muneeb-ali** [comment] 2016-04-08 16:13
You can talk to the server, so that's not the issue. 

> registering and updating fails when trying from my work connection, but works from a home connectio

How does it fail? What's the error that you see?

**Comment by TravisLittlechilds** [comment] 2016-04-08 16:20
Yesterday, and this morning when it happened I would get this error:

"error": "Couldn't broadcast transaction. You can try again."

However, upon trying it right now, it seems to work again as expected. :/ Sorry this seems to be not possible to replicate for me.

**Comment by muneeb-ali** [comment] 2016-04-08 17:13
Got it. I can confirm that it's not a firewall issue. 

We're already working on replacing the "Couldn't broadcast transaction" with more detailed/helpful messages and hopefully that will help if you ever encounter this again. Once again thanks for taking the time to give us feedback! It really helps :-)

**Comment by jcnelson** [comment] 2017-03-20 22:18
Closing this issue here.  If problem persists, please re-open in the blockstack-core repo.

**Closed as completed by jcnelson** 2017-03-20 22:18 UTC
