### ISSUE TITLE
Storage methods do not work when minified/uglified

### ISSUE THREAD

**Issue by patrickdevivo** [stx-labs/stacks.js#294] opened 2017-11-13 04:11 UTC
Following up on the discussion in this Slack thread: https://blockstack.slack.com/archives/C074LC7RC/p1510523398000023

It appears that minifying/uglifying `blockstack.js` caused problems with the `bitcoinjs` dependency. Not sure of a good way around this without addressing the issue in the dependency lib.

At the very least, this should probably be documented someplace central/accessible so people know of the issue - this makes using this package in `create-react-app` or similar environments difficult.

I discovered when trying to use `putFile` and `getFile` in minified code

**Comment by brandonparee** [comment] 2017-11-13 06:22
I agree with documenting the issue somewhere, especially since the issue is related to a dependency and not the package itself. 

The solution is documented in the README for [`bitcoinjs-lib`](https://github.com/bitcoinjs/bitcoinjs-lib)

A relevant excerpt: 

> NOTE: If you uglify the javascript, you must exclude the following variable names from being mangled: BigInteger, ECPair, Point. This is because of the function-name-duck-typing used in typeforce.

As far as using `create-react-app` goes, I believe that for a production build you need to use the `eject` command given by `create-react-app` and modify the `config/webpack.config.prod.js`. 

You'll need to add `except: ['BigInteger', 'ECPair', 'Point']` inside of the `mangle` object in the `UglifyJSPlugin` call. (It should be around line 275)

**Comment by larrysalibra** [comment] 2018-01-12 10:14
I've opened an issue to add these instructions to our readme #345 - going to close this issue out. Thanks for bringing this up!

**Closed as completed by larrysalibra** 2018-01-12 10:14 UTC
