### ISSUE TITLE
validateProof broken for Instagram

### ISSUE THREAD

**Issue by shreyasthiagaraj** [stx-labs/stacks.js#609] opened 2019-02-18 17:14 UTC
They seem to have changed their layout, so tests are failing.

**Comment by yknl** [comment] 2019-03-06 23:04
I was unable to reproduce this. I successfully added and verified this Instagram proof: https://www.instagram.com/p/Buo-NJ9hKSx/

**Comment by yknl** [comment] 2019-04-23 19:08
Closing as cannot reproduce.

**Closed as completed by yknl** 2019-04-23 19:08 UTC
Labels: bug
